/**
 * Persistent OAuth state store backed by SQLite.
 *
 * Replaces the per-provider in-memory Maps. State survives server restarts
 * and cold starts (e.g. Render free tier), so in-flight OAuth flows are not
 * lost when the process is recycled between the user clicking "Connect" and
 * the provider redirecting back to the callback.
 *
 * States expire after TTL_MINUTES and are lazily pruned on each read/write.
 */

import { db } from '../config/database.js';

const TTL_MINUTES = 15;

// Create the table once on module load
db.exec(`
  CREATE TABLE IF NOT EXISTS oauth_states (
    state      TEXT PRIMARY KEY,
    provider   TEXT NOT NULL,
    user_id    TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TEXT NOT NULL
  );
  CREATE INDEX IF NOT EXISTS idx_oauth_states_expires ON oauth_states(expires_at);
`);

function expiresAt() {
	const d = new Date();
	d.setMinutes(d.getMinutes() + TTL_MINUTES);
	return d.toISOString();
}

function pruneExpired() {
	db.prepare(`DELETE FROM oauth_states WHERE expires_at <= ?`).run(new Date().toISOString());
}

/**
 * Save a new OAuth state token linked to a provider + userId.
 * @param {string} state  - UUID generated by the provider service
 * @param {string} provider - e.g. 'google_drive'
 * @param {string} userId - OmniCloud user ID
 */
export function saveOAuthState(state, provider, userId) {
	pruneExpired();
	db.prepare(`
    INSERT OR REPLACE INTO oauth_states (state, provider, user_id, expires_at)
    VALUES (?, ?, ?, ?)
  `).run(state, provider, userId, expiresAt());
}

/**
 * Consume a state token. Returns { userId } or null if missing/expired.
 * The state is deleted on first use (one-time use).
 * @param {string} state
 * @param {string} provider
 * @returns {{ userId: string } | null}
 */
export function consumeOAuthState(state, provider) {
	pruneExpired();
	const row = db.prepare(`
    SELECT user_id FROM oauth_states
    WHERE state = ? AND provider = ? AND expires_at > ?
  `).get(state, provider, new Date().toISOString());

	if (!row) return null;

	db.prepare(`DELETE FROM oauth_states WHERE state = ?`).run(state);
	return { userId: row.user_id };
}
